# Generated by Django 6.0.3 on 2026-04-03 17:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_alter_question_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="question_images/", verbose_name="file"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="order",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="uploaded at"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.question",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "question image",
                "verbose_name_plural": "question images",
                "db_table": "question_images",
                "ordering": ["question", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "order"), name="unique_question_order"
                    )
                ],
            },
        ),
    ]
