# Generated by Django 6.0.3 on 2026-04-04 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0006_alter_question_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="order",
            ),
        ),
    ]
