# Generated by Django 6.0.3 on 2026-04-04 17:53

import django.core.validators
from django.db import migrations, models

import apps.surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0007_alter_question_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionimage",
            name="alt_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="alternative text"
            ),
        ),
        migrations.AlterField(
            model_name="questionimage",
            name="file",
            field=models.ImageField(
                upload_to=apps.surveys.models.question_image_upload_to,
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="questionimage",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="order",
            ),
        ),
    ]
