# Generated by Django 6.0.3 on 2026-04-05 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0009_option_remove_questionimage_unique_question_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="surveys.question",
                verbose_name="question",
            ),
        ),
    ]
