# Generated by Django 6.0.3 on 2026-04-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0010_alter_option_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["question", "order"],
                "verbose_name": "option",
                "verbose_name_plural": "options",
            },
        ),
        migrations.AlterModelTable(
            name="option",
            table="option",
        ),
    ]
