# Generated by Django 6.0.3 on 2026-04-05 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0011_alter_option_options_alter_option_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionimage",
            options={
                "ordering": ["question", "order"],
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
        migrations.AlterField(
            model_name="questionimage",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="surveys.question",
                verbose_name="question",
            ),
        ),
        migrations.AlterModelTable(
            name="questionimage",
            table="images",
        ),
    ]
