# Generated by Django 6.0.3 on 2026-04-15 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0001_initial"),
        ("surveys", "0012_alter_questionimage_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="respondents",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_surveys",
                through="answers.SurveyAccess",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
