# Generated by Django 6.0.3 on 2026-04-03 01:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="edited at"),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="question text"),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="order")),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="is required"),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="surveys.survey",
                        verbose_name="survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "db_table": "questions",
                "ordering": ["survey__title", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("survey", "order"), name="unique_survey_order"
                    )
                ],
            },
        ),
    ]
