# Generated by Django 6.0.3 on 2026-04-03 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="order",
            ),
        ),
    ]
