# Generated by Django 6.0.3 on 2026-04-03 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0004_questionimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionimage",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_images",
                to="surveys.question",
                verbose_name="question",
            ),
        ),
    ]
