# Generated by Django 6.0.3 on 2026-04-04 18:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0008_questionimage_alt_text_alter_questionimage_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "question option",
                "verbose_name_plural": "question options",
                "db_table": "question_options",
                "ordering": ["question", "order"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="questionimage",
            name="unique_question_order",
        ),
        migrations.AlterField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AddConstraint(
            model_name="questionimage",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="unique_question_image_order"
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_options",
                to="surveys.question",
                verbose_name="question",
            ),
        ),
        migrations.AddConstraint(
            model_name="option",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="unique_question_option_order"
            ),
        ),
    ]
